services:
  postgres:
    image: postgres:16
    container_name: popcornpicks_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./.db/createTables.sql:/docker-entrypoint-initdb.d/createTables.sql
      - ./db_data:/var/lib/postgresql/data
    networks:
      - popcornpicks-network

networks:
  popcornpicks-network:
    external: true
